### ISSUE TITLE
User Authentication Issue

### ISSUE THREAD

**Issue by Benz56** [Maximvdw/SpigotSite-API#14]
Authenticating a user via the API results in an NPE.

Using spigotsite-api version 0.3.2-SNAPSHOT and spigotsite version 0.4.1-SNAPSHOT.

Authentication:
```java
spigotUser = spigotSiteCore.getUserManager().authenticate(
        username,
        password,
        twofa
);
```
Causing
```java
java.lang.NullPointerException
	at be.maximvdw.spigotsite.user.SpigotUserManager.authenticate(SpigotUserManager.java:101)
	at be.maximvdw.spigotsite.user.SpigotUserManager.authenticate(SpigotUserManager.java:78)
```

Caused by the response values being null. Exceptions occurs here:
```java
if (res.getResponseURL().toString().startsWith("https://www.spigotmc.org/login/two-step")) {
```
Where the response is:
<img width="200" alt="Debug" src="https://user-images.githubusercontent.com/32618140/105603914-0e389980-5d96-11eb-841c-5fb4a3cd4c61.png">

Similar to issue #13 with some extra details.

**Comment by Benz56** [comment]
Some more details:
The post method in the JsoupRequest class file throws an exception. The HTTP response code of the request is 503. This is most likely caused by Cloudflare blocking non-human requests.

**Comment by Osiris-Team** [comment]
@Benz56 yep. More details here: https://github.com/Osiris-Team/AutoPlug-Client/issues/6
